### ISSUE TITLE
Add an Address variable

### ISSUE THREAD

**Issue by alazare619** [WilliamJBrown/WatcherDocker#1]
I have created a json file for the distro rockstor so it can run watcher (Rockstor is a Nas) being a NAS it is headless so I need the ability to change the address from 127.0.0.1 to 0.0.0.0. Please add such functionality.

https://gist.github.com/alazare619/dd5e52eb29cb6119385cef760fa1e788

**Comment by alazare619** [comment]
I'm thinking this line

exec runuser -l watcher -c 'python /opt/watcher/app/watcher.py --conf /config/config.cfg --log /log/ --db /database/database.sqlite' 

Could just be changed to

exec runuser -l watcher -c 'python /opt/watcher/app/watcher.py --conf /config/config.cfg --log /log/ --db /database/database.sqlite --address ${Address}'

and add a ENV on the docker file i'm not positive however i'm by no means versed in docker.

**Comment by alazare619** [comment]
Added Server Address Variable to dockerfile -https://gist.github.com/alazare619/b1f57bff27ffb48adc52de02352f2131

Added Server Address in the Run String -
https://gist.github.com/alazare619/dd7eb08c81c8d6f5db2540092100c1c8

I Believe these should work

**Comment by alazare619** [comment]
Pull Request Created
https://github.com/WilliamJBrown/WatcherDocker/pull/2

**Comment by WilliamJBrown** [comment]
You can define the path of the config file. You just have to manually adjust the config file once you boot it up and shut it down. This is done to prevent not so technical people exposing the application without knowing what they are doing. For the technical people you can just edit the config file.

**Comment by alazare619** [comment]
Define the variable with 127.0.0.1 so if its not defined it will default to
local host. but if defined to 0.0.0.0 it will listen on any ip. Also if you
are using docker you arent a NON technical person anyways...

**Comment by WilliamJBrown** [comment]
Docker was made for non technical deployment. Makes it easier to set these applications up.
